Repository Frankeo/interview-tool, pull requests merged in 2020-12, with the labels that each got.

#75 Setup ESLint and Prettier
  .eslintrc.json
  index.js
  jest.config.js
  package-lock.json
  package.json
  pull_request_template.md
  src/add-module/command.js
  src/add-module/command.test.js
  src/add-module/project-integrity.js
  src/add-module/project-integrity.test.js
  src/create-module/command.test.js
  src/deploy-module/command.test.js
  src/list-module/command.test.js
  src/services/formatting.js
  src/services/formatting.test.js
  src/services/output-project.js
  src/services/output-project.test.js
  typedefs.js
Labels: todo :spiral_notepad:

#89 Feature/60 setup husky
  .github/workflows/build.yml
  .husky/.gitignore
  .husky/pre-push
  .vscode/settings.json
  README.md
  jest.config.js
  package-lock.json
  package.json
  src/list-module/command.js
  src/list-module/command.test.js
  src/services/formatting.js
Labels: size/M

#91 Feature/37 code factor
  package.json
  src/create-module/command.js
Labels: size/S

#94 Feature/69 add multiple projects
  pull_request_template.md
  src/add-module/command.js
  src/add-module/command.test.js
  src/add-module/project-integrity.js
  src/db/db-management.js
Labels: size/M

#101 Adding release 2.0.0
  README.md
  package.json
Labels: release, size/XS

#104 build(changelog): setup Commitizen
  .husky/prepare-commit-msg
  package-lock.json
  package.json
Labels: dependencies, documentation, size/S

#106 (refactor) Remove unused constants
  src/add-module/command.js
  src/add-module/project-integrity.js
  src/constants.js
  src/deploy-module/command.js
  src/list-module/command.js
  src/list-module/command.test.js
  src/services/formatting.test.js
Labels: enhancement, size/M
